REPORT Z_ALGJ_25.

 TABLES:
   SKA1.

 TYPES:

   BEGIN OF TYPE_SKA1,
     KTOPL TYPE SKA1-KTOPL,
     SAKNR TYPE SKA1-SAKNR,
     ERDAT TYPE SKA1-ERDAT,
   END OF TYPE_SKA1,

   BEGIN OF TYPE_SKB1,
     BUKRS TYPE SKB1-BUKRS,
     SAKNR TYPE SKB1-SAKNR,
   END OF TYPE_SKB1,

   BEGIN OF TYPE_T001,
     BUKRS TYPE T001-BUKRS,
     BUTXT TYPE T001-BUTXT,
     LAND1 TYPE T001-LAND1,
   END OF TYPE_T001,

   BEGIN OF TYPE_SKAT,
     SPRAS TYPE SKAT-SPRAS,
     KTOPL TYPE SKAT-KTOPL,
     SAKNR TYPE SKAT-SAKNR,
     TXT20 TYPE SKAT-TXT20,
   END OF TYPE_SKAT.

 DATA:
   TI_SKA1 TYPE TABLE OF TYPE_SKA1,
   TI_SKB1 TYPE TABLE OF TYPE_SKB1,
   TI_T001 TYPE TABLE OF TYPE_T001,
   TI_SKAT TYPE TABLE OF TYPE_SKAT.

 DATA:
   WA_SKA1 TYPE TYPE_SKA1,
   WA_SKB1 TYPE TYPE_SKB1,
   WA_T001 TYPE TYPE_T001,
   WA_SKAT TYPE TYPE_SKAT.

 DATA:
   V_EMPRESA    TYPE SKB1-BUKRS,
   V_CONTADOR   TYPE I,
   V_CONTADOR_2 TYPE I.

 SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.

 SELECT-OPTIONS S_SAKNR FOR SKA1-SAKNR.

 SELECTION-SCREEN: END OF BLOCK B1.

 FREE TI_SKA1.
 SELECT KTOPL
        SAKNR
        ERDAT
 FROM SKA1
 INTO TABLE TI_SKA1
 WHERE SAKNR IN S_SAKNR
   AND KTOPL = 'INT'.

 IF SY-SUBRC <> 0.
   FREE TI_SKA1.
   MESSAGE 'Dados não encontrados!' TYPE 'S' DISPLAY LIKE 'S'.
   LEAVE LIST-PROCESSING.
 ENDIF.

 IF TI_SKA1 IS NOT INITIAL.

   FREE TI_SKB1.
   SELECT BUKRS
          SAKNR
     FROM SKB1
     INTO TABLE TI_SKB1
      FOR ALL ENTRIES IN TI_SKA1
    WHERE SAKNR = TI_SKA1-SAKNR.

   IF SY-SUBRC <> 0.
     FREE TI_SKB1.
   ENDIF.

 ENDIF.

 IF TI_SKB1 IS NOT INITIAL.

   FREE TI_T001.
   SELECT BUKRS
          BUTXT
          LAND1
     FROM T001
     INTO TABLE TI_T001
      FOR ALL ENTRIES IN TI_SKB1
    WHERE BUKRS = TI_SKB1-BUKRS
      AND LAND1 = 'BR'.

   IF SY-SUBRC <> 0.
     FREE TI_T001.
   ENDIF.

 ENDIF.

 IF TI_SKA1 IS NOT INITIAL.

   FREE TI_SKAT.
   SELECT SPRAS
          KTOPL
          SAKNR
          TXT20
     FROM SKAT
     INTO TABLE TI_SKAT
      FOR ALL ENTRIES IN TI_SKA1
    WHERE SPRAS = 'PT'
      AND KTOPL = 'INT'
      AND SAKNR = TI_SKA1-SAKNR.

   IF SY-SUBRC <> 0.
     FREE TI_SKAT.
   ENDIF.

 ENDIF.

 SORT: TI_SKA1 BY SAKNR,
       TI_SKB1 BY SAKNR
                  BUKRS,
       TI_T001 BY BUKRS,
       TI_SKAT BY SAKNR.

 LOOP AT TI_SKA1 INTO WA_SKA1.

   CLEAR WA_SKB1.
   READ TABLE TI_SKB1 INTO WA_SKB1 WITH KEY
                                   SAKNR = WA_SKA1-SAKNR BINARY SEARCH.

   CLEAR WA_T001.
   READ TABLE TI_T001 INTO WA_T001 WITH KEY
                                   BUKRS = WA_SKB1-BUKRS BINARY SEARCH.

   CLEAR WA_SKAT.
   READ TABLE TI_SKAT INTO WA_SKAT WITH KEY
                                   SAKNR = WA_SKA1-SAKNR BINARY SEARCH.

   IF V_EMPRESA <> WA_SKB1-BUKRS.

     IF V_EMPRESA IS NOT INITIAL.
       FORMAT RESET.
       FORMAT COLOR COL_TOTAL INTENSIFIED OFF.

       WRITE:
           /1   '|', 'Total de contas do razão para a empresa ', WA_SKB1-BUKRS, ' =', V_CONTADOR_2,
           90   '|'.
     ENDIF.

     CLEAR: V_CONTADOR_2.

     FORMAT RESET.
     FORMAT COLOR COL_HEADING INTENSIFIED OFF.

     WRITE:
         /1   '|', 'Empresa',
         30   '|', 'Denominação da firma ou empresa',
         90   '|'.

     FORMAT RESET.
     FORMAT COLOR COL_POSITIVE INTENSIFIED OFF.

     WRITE:
        /1   '|', WA_SKB1-BUKRS,
        30   '|', WA_T001-BUTXT,
        90   '|'.


     FORMAT RESET.
     FORMAT COLOR COL_HEADING INTENSIFIED OFF.

     WRITE:
         /1   '|', 'N° conta do Razão',
         30   '|', 'Data de criação do registro',
         60   '|', 'Texto das contas do Razão',
         90   '|'.

     V_EMPRESA = WA_SKB1-BUKRS.

   ENDIF.

   FORMAT RESET.
   FORMAT COLOR COL_POSITIVE INTENSIFIED OFF.

   WRITE:
       /1   '|', WA_SKA1-SAKNR,
       30   '|', WA_SKA1-ERDAT,
       60   '|', WA_SKAT-TXT20,
       90   '|'.


   FORMAT RESET.
   FORMAT COLOR COL_TOTAL INTENSIFIED OFF.

   V_CONTADOR_2 = V_CONTADOR_2 + 1.
   V_CONTADOR = V_CONTADOR + 1.

 ENDLOOP.

 FORMAT RESET.
 FORMAT COLOR COL_TOTAL INTENSIFIED OFF.

 WRITE:
     /1   '|', 'Total de contas do raz�o para a empresa ', WA_SKB1-BUKRS, ' =', V_CONTADOR_2,
     90   '|'.

 WRITE:
     /1   '|', 'Total de registros selecionados =', V_CONTADOR,
     90   '|'.